AllCops:
  Exclude:
    - "spec/dummy/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Max: 120
  Exclude:
    - "spec/simple_scheduler/task_spec.rb"

Style/IndentArray:
  Exclude:
    - "spec/simple_scheduler/task_spec.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes
